version: "3.8"

services:
  express-app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.express-demo-app.rule=Host(`express-demo-app.traefik.me`)"
      - "traefik.http.services.express-demo-app.loadbalancer.server.port=3000"
    networks:
      - web
    expose:
      - "3000"

  traefik:
    image: "traefik:v3.2"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web:
    external: true
